//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.

namespace CityParkWeb.Entities.Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoMultas
    {
        public int TipoMultaId { get; set; }
        public string Multa { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public Nullable<double> Porcentaje { get; set; }
        public Nullable<int> SalarioBasicoId { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual ICollection<Multa> Multa1 { get; set; }
        public virtual SalarioBasico SalarioBasico { get; set; }
    }
}
